### ISSUE TITLE
Copyright Issue

### ISSUE THREAD

**Issue by qbhx224** [NRTnarathip/SMAPILoader#10]

**Comment by NRTnarathip** [comment]
I cannot control it.
And of course, I am currently focusing on fixing bugs and developing the app.
Thank you for the report. ❤️❤️🙏

**Comment by AozoraDev** [comment]
@qbhx224 
What copyright issue are you talking about?

**Comment by equalDelight** [comment]
> @qbhx224 What copyright issue are you talking about?

He probably downloaded the game off internet and not playstore.
