### ISSUE TITLE
The game is no longer available Online  after installing SMAPI

### ISSUE THREAD

**Issue by sakoao** [NRTnarathip/SMAPILoader#11]
My little friend and I were able to go online. However, SMAPI cannot be online after it is launched. And I asked a lot of people to do the same. You can also find different models to test. Please reply as soon as possible, thanks

**Comment by NRTnarathip** [comment]
SMAPI Bug on coop mode, please wait to fix
i don't know how to fix

**Comment by sakoao** [comment]
感谢回复。请问是所有手机都这样还是部分。

**Comment by sakoao** [comment]
Thank you for your reply. May I ask if all phones are like this or only some.

**Comment by NRTnarathip** [comment]
you can update download in my discord

**Comment by sakoao** [comment]
thank you

**Comment by sakoao** [comment]
but why busy task get stuck

**Comment by sakoao** [comment]
oh sorry,The simulator will get stuck, but the real machine won't
