### ISSUE TITLE
Farm Type Manager Game characters cannot move

### ISSUE THREAD

**Issue by kkya6233** [NRTnarathip/SMAPILoader#15]
Game version 1.6.14.11 SMAPI version 4.1.7.6 Farm Type Manager version 1.24.0
There is no display error and the game character moves directly and crashes

**Comment by LiDevil** [comment]
same problem

**Comment by NRTnarathip** [comment]
i fixed in SMAPI tester, you can update & test it
don't forget tag me if you stuck this bug

**Comment by LiDevil** [comment]
> i fixed in SMAPI tester, you can update & test it don't forget tag me if you stuck this bug

thanks，it work now，i use ver 1.0.14
