### ISSUE TITLE
MonoMod cannot modify protected fields or methods

### ISSUE THREAD

**Issue by Fireworkshh** [NRTnarathip/SMAPILoader#17]
Most mods on Nexus Mods use MonoMod to modify protected fields or methods, which can cause crashes, meaning we have to adjust the mods one by one.

**Comment by Fireworkshh** [comment]
This won't happen even in 1.5. It's better to do something more meaningful than spending all this time and energy adjusting the mod.

**Comment by NRTnarathip** [comment]
you can use Bypass 'Field&Method Access Exception' with this code
https://github.com/NRTnarathip/SMAPILoader/blob/master/SMAPIGameLoader/Launcher/BypassAccessException.cs

but!! some device it's not works, i have code patch bytes is run works fine
i have no idea to fix

**Comment by NRTnarathip** [comment]
Src code
https://github.com/dotnet/runtime/blob/c969265440b74e95429fb513e6d940d6c9bc2fd3/src/mono/mono/metadata/class.c#L6535

https://github.com/dotnet/runtime/blob/c969265440b74e95429fb513e6d940d6c9bc2fd3/src/mono/mono/metadata/class.c#L6535

**Comment by Fireworkshh** [comment]
Thank you very much, my other project can only use net6 android to solve this problem at the moment is not smapi, maybe you can use net6 android to solve this problem, I have a way to make net6 android can also support debugging
