### ISSUE TITLE
Just need a little direction 

### ISSUE THREAD

**Issue by Dani141990** [NRTnarathip/SMAPILoader#18]
Is this a smapi problem or Cloudy Skies problem? 

### SMAPI Log Latest
> [Click Link Log Here](https://smapi.io/log/4c3568f6e8b2424484fadcfbfbcfaed0)
> [Click Link Log Here](https://smapi.io/log/4c3568f6e8b2424484fadcfbfbcfaed0)
### Current App Info
> Game 1.6.15.0
> Launcher 1.1.1
> SMAPI 4.1.10.1 - 1734885408

**Comment by NRTnarathip** [comment]
Cloudy Skies
