### ISSUE TITLE
Can't install SMAPI

### ISSUE THREAD

**Issue by dongfengNrq** [NRTnarathip/SMAPILoader#19]
_Launcher Version:1.1.1
Build: 00:06:35 24/12/2024 (d/m/y)
Support Game Version: 1.6.15.0 Or Later
Your Game Version: 1.6.15.0

SMAPI Log Error
System.Exception: Not found file /
storage/emulated/0/Android/
data/abc.smapi.gameloader/files/
ErrorLogs/SMAPI-latest.txt_

I think it's because Android 11＋ cannot access Android/data folder. Could you please add support to Shizuku or some other solutions？

**Comment by NRTnarathip** [comment]
what happen

**Comment by dongfengNrq** [comment]
I use the latest version of game and SMAPI launcher so far, but the installation failed, and the error log is shown above.

**Comment by NRTnarathip** [comment]
Ask me in discord
https://discord.com/invite/ETtycvcJjr
