### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by KazilanBigAss** [NRTnarathip/SMAPILoader#20]
My game turns out like this after I install the tractor mod.
![Screenshot_20241225_232547](https://github.com/user-attachments/assets/139a637e-acad-405b-b5ca-69b66cb6e461)

**Comment by KazilanBigAss** [comment]
[SMAPI-latest.txt](https://github.com/user-attachments/files/18246507/SMAPI-latest.txt)
this is my game log

**Comment by NRTnarathip** [comment]
Delete file files/Saves/EMERGENCY_SAVE
