### ISSUE TITLE
The problem of translation mods

### ISSUE THREAD

**Issue by Nhincaije** [NRTnarathip/SMAPILoader#3]
As you know, in version 1.6, there are translation mods such as Vietnamese, Thai, and others. These mods do not replace any existing language in the game but instead create a separate option for that language. I hope you can add this feature as well.

**Comment by NRTnarathip** [comment]
Oh sorry, you can use mod Localization such as Thai

**Comment by NRTnarathip** [comment]
when you install mod Localize you need mod change language to Mod

**Comment by Nhincaije** [comment]
> [ImproveGame.zip](https://github.com/user-attachments/files/17903793/ImproveGame.zip)
> You need to install Improve Game & Click Right center button & done enjoy❤️
> ![image](https://github.com/user-attachments/assets/ce33d69c-922b-4331-8344-ad928f00723e)
> 

There was a slight problem, as the button did not respond when I pressed it.

**Comment by Nhincaije** [comment]
> > [ImproveGame.zip](https://github.com/user-attachments/files/17903793/ImproveGame.zip)
> > You need to install Improve Game & Click Right center button & done enjoy❤️
> > ![image](https://github.com/user-attachments/assets/ce33d69c-922b-4331-8344-ad928f00723e)
> > 
> 
> There was a slight problem, as the button did not respond when I pressed it.

**Comment by Nhincaije** [comment]
> [ImproveGame.zip](https://github.com/user-attachments/files/17903793/ImproveGame.zip)
> You need to install Improve Game & Click Right center button & done enjoy❤️
> ![image](https://github.com/user-attachments/assets/ce33d69c-922b-4331-8344-ad928f00723e)
> 

There is a problem with the pen it doesn't respond when I press it.
[SMAPI-latest.txt](https://github.com/user-attachments/files/17906869/SMAPI-latest.txt)
