### ISSUE TITLE
the same error as before. 

### ISSUE THREAD

**Issue by Sllay** [NRTnarathip/SMAPILoader#6]
** Every time I try to enter the app it tells me to install it from the play store. **

**Comment by NRTnarathip** [comment]
buy game

**Comment by Sllay** [comment]
> buy game

 I use play pass

**Comment by NRTnarathip** [comment]
Oh, so contact me discord https://discord.com/invite/ETtycvcJjr

**Comment by sakoao** [comment]
may know the question of Domestic lock-up

**Comment by NRTnarathip** [comment]
sorry what question

**Comment by sakoao** [comment]
Restricted from sale in locked areas

**Comment by sakoao** [comment]
We don't even have sv on our Google store in locked areas
We have already supported the author on Steam only able
