### ISSUE TITLE
Issue Sharing

### ISSUE THREAD

**Issue by DoKrips** [NRTnarathip/SMAPILoader#7]
1. When installing, the file name must be "SMAPI-4.1.7.2.zip" to be selected.
2. However, the selected file is not installed.
3. After installing SMAPI on the PC, if you paste the result into "Stardew Assemblies", it appears to be installed.
4. However, when you run it, it does not run with the following error.
![1](https://github.com/user-attachments/assets/9ce60221-89da-47bb-b8f0-da9478b00285)

**Comment by NRTnarathip** [comment]
contact me discord https://discord.com/invite/ETtycvcJjr

**Comment by equalDelight** [comment]
Same issue here

**Comment by NRTnarathip** [comment]
https://discord.com/invite/ETtycvcJjr
contact me on discord, please
