### ISSUE TITLE
virtual keyboard This mode is required.

### ISSUE THREAD

**Issue by wally232** [NRTnarathip/SMAPILoader#8]
**virtual keyboard**
There is no above mode.
Mobile requires above mode to use shortcuts.

**console commands**
There is no above mode either.
Can't mobile use command prompts?

**Comment by NRTnarathip** [comment]
we will update in next month please wait

**Comment by mspzyzh** [comment]
> 我们将在下个月更新，请等待
Looking forward to your good news

**Comment by sakoao** [comment]
Why can't I connect online after installing SMAPI
And The original version is now available online at the same time

**Comment by AozoraDev** [comment]
@sakoao 
Wrong place, m8.
Pls create another issue.

**Comment by sakoao** [comment]
ok  I have withdrawn it @AozoraDev

**Comment by NRTnarathip** [comment]
@wally232 Hello
for now you can use Virtual Keyboard v2.0.2 for SMAPI 4.1.7.5-beta 
download here:
https://github.com/NRTnarathip/VirtualKeyboard/releases
