### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Nhincaije** [NRTnarathip/SMAPILoader#9]
I'm just curious why SMAPI now requires purchasing the game to use. Why was this change necessary? (I already bought the game, but I'm just wondering and also trying to answer questions for my community).

**Comment by NRTnarathip** [comment]
what? why are you try to support crack or pirate apk?

**Comment by NRTnarathip** [comment]
respect "License" and "Law" pro
we working hard, free & open source
no paid, no donate

**Comment by NRTnarathip** [comment]
can you share your link community?

**Comment by Nhincaije** [comment]
> what? why are you try to support crack or pirate apk?

 I want to clarify that I don’t support cracked or pirated games — I even dislike them. I asked because many in my community use pirated versions, and I want to explain to them why SMAPI now requires a legitimate purchase to use. Thanks for your hard work!

**Comment by equalDelight** [comment]
Just tell them that the SMAPI Android dev. doesn't support piracy.
